


**实际使用中多线程使用 CompletableFuture**

**我们平常情况下，使用Future的时候并不多，因为它会阻塞我们的请求，future.get方法会阻塞**
- https://blog.csdn.net/Kevin_King1992/article/details/105968216

**execute的方式，错误也是无法捕捉。其实我们可以曲线救国的绕一下去解决。解决方式就是使用ThreadFactory，实现它的UncaughtExceptionHandler**

## ThreadExecutorExecuteTest.java


```java
/**
 * 使用 Executors 工具类创建线程池
 */
public class ThreadExecutorExecute implements Runnable{

    @Override
    public void run() {
        int i =1/0;
        System.out.println(Thread.currentThread().getName() + " run()方法执行中...");
    }

    public static void main(String[] args) {

        ThreadExecutorExecute myRunnable = new ThreadExecutorExecute();

        ThreadFactory factory = r->{
            Thread thread = Executors.defaultThreadFactory().newThread(myRunnable);
            thread.setUncaughtExceptionHandler( (t,e) -> {
                System.out.println(t + "1111111" + e);
                e.printStackTrace();//example
            });
            return thread ;
        };

        ExecutorService executorService = Executors.newFixedThreadPool(20,factory);
        
        /** 提交多个任务,50 */
        for (int i = 0; i < 50; i++) {
            /**
             * 创建任务对象,并提交给线程池
             * 1. execute只能接受Runnable类型的任务
             * 2. execute没有返回值
             * 3.execute中可以抛出异常，所以使用try、catch来捕获
             */
            executorService.execute(myRunnable);

        }

        System.out.println("线程任务开始执行");
        executorService.shutdown();
    }

}

```



## submit中Runnable和callable两者的区别是

入参为Runnable时，返回值为null
入参为callable时，有返回值




## 参考

- https://blog.csdn.net/qq_27376871/article/details/82965329

- https://zhuanlan.zhihu.com/p/170320272